// ============================================================
// ARTISTS DATA FOR LISTENING ROOM
// ============================================================
// 
// HOW TO ADD A NEW ARTIST:
// 1. Place audio files in: public/audio/
// 2. Place video files in: public/video/ (optional)
// 3. Add a new Artist object to the artists array below
// 
// ============================================================

export interface Artist {
  id: string;
  name: string;
  trackTitle: string;
  bio: string;
  audio?: string;
  video?: string;
  coverImage?: string;
  links?: {
    instagram?: string;
    youtube?: string;
    spotify?: string;
    website?: string;
  };
}

export const artists: Artist[] = [
  {
    id: "rai",
    name: "Ra-I",
    trackTitle: "Xam",
    bio: "Audio Produced by Blue Ape Visuals by Bradford Keeney edited by ABOXAN ARTS",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124112/RA_I_-_XAM_G0j0Xupn8nk_kjbhdv.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770123038/videoplayback_jqzcb8.mp4",
    links: {
      youtube: "https://www.youtube.com/@indigenous4206",
    },
  },
  {
    id: "nikosi",
    name: "Nikosi",
    trackTitle: "SeeGold",
    bio: "Official Music Video of Nikosi Presenting SeeGold Video Shot, Edited & Directed by Safiyah Chiniere Produced by Xavior Jordan Co-Directed & Co-Produced by Nikosi",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124130/Nikosi_-_SeeGold_Official_Music_Video_ssrjjg.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770123332/Nikosi_-_SeeGold_Official_Music_Video_eb2vu8.mp4",

    links: {
      youtube: "https://youtube.com/@nikosi?si=S2rIY_TUCuhqDrmH",
      website: "https://seegoldempire.family.blog",
      instagram: "https://www.instagram.com/nikosi",
      spotify: "https://open.spotify.com/artist/59niWU3AnNT5qN5tPcVwFE?si=oKxNi75aS-Wi5mqH2vgYYA",  

    },
  },
  {
    id: "louiex",
    name: "Louie x Misfit",
    trackTitle: "@SHANI NOMBA",
    bio: "Zambia Rise Up!",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124126/LOUIE_X_FEAT_MISFIT_SHANI_NOMBA_ac4gn1.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124060/LOUIE_X_FEAT_MISFIT_SHANI_NOMBA_gw0yqb.mp4",
    links: {
      youtube: "https://www.youtube.com/@Louie-Xofficial",
      
    },
  },
  {
    id: "azlink",
    name: "Azlink",
    trackTitle: "Pemi",
    bio: "I'm Blvck Music",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124206/PEMI_AZLINK_d3q5vt.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770122868/azlinkvid_toafbb.mp4",
    links: {
      youtube: "https://youtube.com/@danjumaazlink?si=CllKLs5KTmwlV167",
      
    },
  },
  {
    id: "chanttynatural",
    name: "Chantty Natural",
    trackTitle: "Mmalefatshe",
    bio: "Provided to YouTube by CDBaby Mmalefatshe · Chantty Natural Tswanshall2020 Chantty Natural Released on: 2020-09-12 Auto-generated by YouTube.",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124161/ytmp3free.cc_mmalefatshe-youtubemp3free.org_gkfymr.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770123051/Mmalefatshe_l4nuqm.mp4",

    links: {
      youtube: "https://youtube.com/@chanttynaturaltswanshall?si=lePUjscHmy1Wzd6j",
      spotify: "https://open.spotify.com/artist/0ppexZS2JV7yIg5qcYo0yr?si=ryTHcCvlT6eG1VlDcBf5DQ&nd=1&dlsi=a6d8b4b7b6204d4c",
      instagram: "https://www.instagram.com/chanttynatural/",
      website: "https://www.chanttynatural.com/",
    },
  },
   {
    id: "flawlessprodiigy",
    name: "FlawleSs Prodiigy",
    trackTitle: "Control",
    bio: "EDITED BY: Karabxw Blackid",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124204/Control_-_FlawleSs_Prodiigy_qndunc.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770123068/07.Control_Official_Lyric_Video_jpdfcm.mp4",

    links: {
      youtube: "https://www.youtube.com/@flawlessprodiigy",
    },
  },
  {
    id: "taflion",
    name: "Ninja Lady",
    trackTitle: "Nherera",
    bio: "TafLionInternational",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770204283/ninja-lady-amai-prod-by-taf-lion-black-schema-riddim-128-ytshorts.savetube.me_1_cbcnzr.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770204320/Ninja_Lady-_Amai_Prod_by_Taf_Lion_Black_Schema_Riddim_ehc40d.mp4",

    links: {
      youtube: "https://www.youtube.com/watch?v=n9Jan0aYbUE",
      instagram: "https://www.instagram.com/Taf_Lion_International/",
      spotify: "https://open.spotify.com/artist/55Zo1OgS2xMwJUIgHwqWtE?si=of3YKxOwQPioK4FM5d1J0A",
    },
  },

  
  {
    id: "nikosi-superstar",
    name: "Nikosi",
    trackTitle: "Superstar",
    bio: "Official Music Video of Nikosi Presenting SeeGold Video Shot, Edited & Directed by Safiyah Chiniere Produced by Xavior Jordan Co-Directed & Co-Produced by Nikosi",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124210/Nikosi_-_Superstar_Official_Music_Video_ofhpkz.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770123885/Nikosi_-_Superstar_Official_Music_Video_yblteq.mp4",

    links: {
      youtube: "https://youtube.com/@nikosi?si=S2rIY_TUCuhqDrmH",
      website: "https://seegoldempire.family.blog",
      instagram: "https://www.instagram.com/nikosi",
      spotify: "https://open.spotify.com/artist/59niWU3AnNT5qN5tPcVwFE?si=oKxNi75aS-Wi5mqH2vgYYA",  

    },
  },
  {
    id: "louiex-sweetie-wandi",
    name: "Louie x Misfit",
    trackTitle: "Sweetie Wandi",
    bio: "Music video by the legend Louie X featuring the talented songbird Misfit.",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124219/Sweety_Wandi_by_Louie_X_featuring_Misfit_zrqd1p.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770123994/Sweety_Wandi_by_Louie_X_featuring_Misfit_c5dqqn.mp4",
    links: {
      youtube: "https://www.youtube.com/@Louie-Xofficial",
      
    },
  },
   {
    id: "azlink-darego",
    name: "Azlink x Gudhee",
    trackTitle: "Darego",
    bio: "i'm Blvck Music",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124117/AZLINK_X_GUDHEE_-_DAREGO_MM_SIQESTSOUND_uqbgyg.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770122868/azlinkvid_toafbb.mp4",
    links: {
      youtube: "https://youtube.com/@danjumaazlink?si=CllKLs5KTmwlV167",
      
    },
  },
  // {
  //   id: "chanttynatural2",
  //   name: "Chantty Natural",
  //   trackTitle: "Rato la Pelo",
  //   bio: "Provided to YouTube by CDBaby Mmalefatshe · Chantty Natural Tswanshall2020 Chantty Natural Released on: 2020-09-12 Auto-generated by YouTube.",
  //   audio: "/audio/ytmp3free.cc_rato-la-pelo-youtubemp3free.org.mp3",
  //   video: "/video/Chantty Natural Rato la Pelo (Official Video).mp4",
  //    links: {
  //     youtube: "https://youtube.com/@chanttynaturaltswanshall?si=lePUjscHmy1Wzd6j",
  //     spotify: "https://open.spotify.com/artist/0ppexZS2JV7yIg5qcYo0yr?si=ryTHcCvlT6eG1VlDcBf5DQ&nd=1&dlsi=a6d8b4b7b6204d4c",
  //     instagram: "https://www.instagram.com/chanttynatural/",
  //     website: "https://www.chanttynatural.com/",
  //   },
  // },
  {
    id: "flawlessprodiigy-black-pill",
    trackTitle: "Black Pill",
    name: "Flawless Prodiigy",
    bio: "EDITED BY: Karabxw Blackid",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1772390367/0.Black_Pill_Prod._By_Karibuchops_vbgoyd.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770122988/0.Black_Pill_Prod._By_Karibuchops_dmrffr.mp4",

    links: {
      youtube: "https://www.youtube.com/@flawlessprodiigy",
    },
  },


  {
    id: "taflion-tarirai",
    name: "Tarirai Remix Taf Lion ft Samoraa, Louie X & VJ Nakasa- Prod by Taf Lion International",
    trackTitle: "Tarirai Remix",
    bio: "(Tribute to Dr Oliver Mtukudzi) #Taf_Lion_International",
    audio: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770124267/ytmp3free.cc_tarirai-remix-taf-lion-ft-samoraa-louie-x-vj-nakasa-prod-by-taf-lion-international-youtubemp3free.org_rlzkue.mp3",
    video: "https://res.cloudinary.com/dyvsfyaze/video/upload/v1770123525/Tarirai_Remix_Taf_Lion_ft_Samoraa_Louie_X_VJ_Nakasa-_Prod_by_Taf_Lion_International_dsaskl.mp4",

    links: {
      youtube: "https://www.youtube.com/watch?v=n9Jan0aYbUE",
      instagram: "https://www.instagram.com/Taf_Lion_International/",
      spotify: "https://open.spotify.com/artist/55Zo1OgS2xMwJUIgHwqWtE?si=of3YKxOwQPioK4FM5d1J0A",
    },
  },


];

// Helper functions
export const getArtistById = (id: string): Artist | undefined => {
  return artists.find((artist) => artist.id === id);
};

export const getNextArtist = (currentId: string): Artist | undefined => {
  const currentIndex = artists.findIndex((artist) => artist.id === currentId);
  if (currentIndex === -1) return undefined;
  return artists[(currentIndex + 1) % artists.length];
};

export const getPreviousArtist = (currentId: string): Artist | undefined => {
  const currentIndex = artists.findIndex((artist) => artist.id === currentId);
  if (currentIndex === -1) return undefined;
  return artists[(currentIndex - 1 + artists.length) % artists.length];
};
