// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Runtime checks to make debugging easier when env vars are not loaded.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Avoid printing the full key in logs, but show presence/absence for diagnostics.
  // This helps explain "Failed to fetch" when the client can't contact Supabase.
  // Ensure you restart the dev server after editing `.env` so Vite picks up the values.
  // Example: `npm run dev` (or `bun run dev`) in PowerShell.
  // Do NOT commit secrets to version control.
  // eslint-disable-next-line no-console
  console.error('[supabase] Missing environment variables:', {
    hasUrl: Boolean(SUPABASE_URL),
    hasPublishableKey: Boolean(SUPABASE_PUBLISHABLE_KEY),
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});